name: Java CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - ghtest1
  pull_request:
    branches:
      - master
      - ghtest1

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew clean build
    - uses: actions/upload-artifact@v2
      with:
        name: dashboard
        path: github-actions-dashboard-server/build/libs/
        retention-days: 1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Debugging
      run: pwd; ls -l; ls -l ./github-actions-dashboard-server/build/libs

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/github-dashboard:latest