name: Deploy Demo

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew clean build
    - name: Set up CF CLI
      if: success()
      uses: jvalkeal/setup-cf-cli@v0
      with:
        version: 6.51.0
    - name: CF Login
      if: success()
      run: cf login -a $CF_API -u $CF_USERNAME -o $CF_ORG -s $CF_SPACE -p $CF_PASSWORD
      env:
        CF_API: ${{ secrets.CF_API }}
        CF_ORG: ${{ secrets.CF_ORG }}
        CF_SPACE: ${{ secrets.CF_SPACE }}
        CF_USERNAME: ${{ secrets.CF_USERNAME }}
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
    - name: Deploy Demo
      if: success()
      run: cf delete -f gh-actions-dashboard-demo && cf push -f .cf/gh-actions-demo-manifest.yml --var clientid=$GH_CLIENTID  --var clientsecret=$GH_CLIENTSECRET --var scope=$GH_SCOPE
      env:
        GH_CLIENTID: ${{ secrets.GH_CLIENTID }}
        GH_CLIENTSECRET: ${{ secrets.GH_CLIENTSECRET }}
        GH_SCOPE: ${{ secrets.GH_SCOPE }}
